input_feeds = [[{'key': 'S', 'pos': 18, 'reward': 336},
                {'key': 'M', 'pos': 12, 'reward': 5},
                {'key': 'T', 'pos': 19, 'reward': 391},
                {'key': 'F', 'pos': 5, 'reward': 211},
                {'key': 'D', 'pos': 3, 'reward': 419}],
               [{'key': 'J', 'pos': 9, 'reward': 424},
                {'key': 'Q', 'pos': 16, 'reward': 335},
                {'key': 'G', 'pos': 6, 'reward': 362},
                {'key': 'E', 'pos': 4, 'reward': 445},
                {'key': 'P', 'pos': 15, 'reward': 115}],
               [{'key': 'P', 'pos': 15, 'reward': 134},
                {'key': 'G', 'pos': 6, 'reward': 325},
                {'key': 'N', 'pos': 13, 'reward': 281},
                {'key': 'R', 'pos': 17, 'reward': 305},
                {'key': 'F', 'pos': 5, 'reward': 428}],
               [{'key': 'B', 'pos': 1, 'reward': 491},
                {'key': 'K', 'pos': 10, 'reward': 210},
                {'key': 'P', 'pos': 15, 'reward': 130},
                {'key': 'Q', 'pos': 16, 'reward': 392},
                {'key': 'F', 'pos': 5, 'reward': 369},
                {'key': 'R', 'pos': 17, 'reward': 166}],
               [{'key': 'A', 'pos': 0, 'reward': 442},
                {'key': 'N', 'pos': 13, 'reward': 241},
                {'key': 'C', 'pos': 2, 'reward': 40},
                {'key': 'Q', 'pos': 16, 'reward': 434},
                {'key': 'L', 'pos': 11, 'reward': 29},
                {'key': 'M', 'pos': 12, 'reward': 312}],
               [{'key': 'I', 'pos': 8, 'reward': 194},
                {'key': 'L', 'pos': 11, 'reward': 183},
                {'key': 'O', 'pos': 14, 'reward': 185},
                {'key': 'D', 'pos': 3, 'reward': 445},
                {'key': 'A', 'pos': 0, 'reward': 20},
                {'key': 'K', 'pos': 10, 'reward': 166}],
               [{'key': 'O', 'pos': 14, 'reward': 120},
                {'key': 'I', 'pos': 8, 'reward': 284},
                {'key': 'R', 'pos': 17, 'reward': 57},
                {'key': 'C', 'pos': 2, 'reward': 3}],
               [{'key': 'I', 'pos': 8, 'reward': 193},
                {'key': 'F', 'pos': 5, 'reward': 244},
                {'key': 'A', 'pos': 0, 'reward': 214},
                {'key': 'K', 'pos': 10, 'reward': 253}],
               [{'key': 'R', 'pos': 17, 'reward': 384},
                {'key': 'H', 'pos': 7, 'reward': 196},
                {'key': 'D', 'pos': 3, 'reward': 56},
                {'key': 'O', 'pos': 14, 'reward': 407}],
               [{'key': 'B', 'pos': 1, 'reward': 150},
                {'key': 'H', 'pos': 7, 'reward': 239},
                {'key': 'J', 'pos': 9, 'reward': 80},
                {'key': 'I', 'pos': 8, 'reward': 219},
                {'key': 'E', 'pos': 4, 'reward': 107},
                {'key': 'L', 'pos': 11, 'reward': 240}],
               [{'key': 'A', 'pos': 0, 'reward': 217},
                {'key': 'T', 'pos': 19, 'reward': 267},
                {'key': 'R', 'pos': 17, 'reward': 432},
                {'key': 'O', 'pos': 14, 'reward': 443}],
               [{'key': 'G', 'pos': 6, 'reward': 24},
                {'key': 'N', 'pos': 13, 'reward': 352},
                {'key': 'S', 'pos': 18, 'reward': 422},
                {'key': 'F', 'pos': 5, 'reward': 338},
                {'key': 'O', 'pos': 14, 'reward': 372}],
               [{'key': 'R', 'pos': 17, 'reward': 96},
                {'key': 'B', 'pos': 1, 'reward': 236},
                {'key': 'P', 'pos': 15, 'reward': 498},
                {'key': 'L', 'pos': 11, 'reward': 149}],
               [{'key': 'M', 'pos': 12, 'reward': 246},
                {'key': 'F', 'pos': 5, 'reward': 247},
                {'key': 'J', 'pos': 9, 'reward': 287},
                {'key': 'A', 'pos': 0, 'reward': 128},
                {'key': 'G', 'pos': 6, 'reward': 290},
                {'key': 'N', 'pos': 13, 'reward': 215}],
               [{'key': 'O', 'pos': 14, 'reward': 140},
                {'key': 'K', 'pos': 10, 'reward': 4},
                {'key': 'H', 'pos': 7, 'reward': 294},
                {'key': 'A', 'pos': 0, 'reward': 378}],
               [{'key': 'H', 'pos': 7, 'reward': 243},
                {'key': 'K', 'pos': 10, 'reward': 264},
                {'key': 'F', 'pos': 5, 'reward': 182},
                {'key': 'Q', 'pos': 16, 'reward': 116}],
               [{'key': 'J', 'pos': 9, 'reward': 99},
                {'key': 'Q', 'pos': 16, 'reward': 374},
                {'key': 'R', 'pos': 17, 'reward': 74},
                {'key': 'M', 'pos': 12, 'reward': 286},
                {'key': 'E', 'pos': 4, 'reward': 17},
                {'key': 'I', 'pos': 8, 'reward': 54}],
               [{'key': 'R', 'pos': 17, 'reward': 140},
                {'key': 'G', 'pos': 6, 'reward': 393},
                {'key': 'T', 'pos': 19, 'reward': 86},
                {'key': 'N', 'pos': 13, 'reward': 488},
                {'key': 'L', 'pos': 11, 'reward': 386},
                {'key': 'F', 'pos': 5, 'reward': 455}],
               [{'key': 'Q', 'pos': 16, 'reward': 84},
                {'key': 'E', 'pos': 4, 'reward': 478},
                {'key': 'B', 'pos': 1, 'reward': 491},
                {'key': 'O', 'pos': 14, 'reward': 149}],
               [{'key': 'A', 'pos': 0, 'reward': 399},
                {'key': 'O', 'pos': 14, 'reward': 373},
                {'key': 'I', 'pos': 8, 'reward': 14},
                {'key': 'R', 'pos': 17, 'reward': 206},
                {'key': 'K', 'pos': 10, 'reward': 317},
                {'key': 'B', 'pos': 1, 'reward': 380}],
               [{'key': 'M', 'pos': 12, 'reward': 113},
                {'key': 'E', 'pos': 4, 'reward': 303},
                {'key': 'F', 'pos': 5, 'reward': 68},
                {'key': 'B', 'pos': 1, 'reward': 198},
                {'key': 'A', 'pos': 0, 'reward': 95},
                {'key': 'C', 'pos': 2, 'reward': 213}],
               [{'key': 'P', 'pos': 15, 'reward': 21},
                {'key': 'E', 'pos': 4, 'reward': 372},
                {'key': 'T', 'pos': 19, 'reward': 495},
                {'key': 'C', 'pos': 2, 'reward': 483},
                {'key': 'J', 'pos': 9, 'reward': 210}],
               [{'key': 'F', 'pos': 5, 'reward': 265},
                {'key': 'N', 'pos': 13, 'reward': 440},
                {'key': 'K', 'pos': 10, 'reward': 292},
                {'key': 'A', 'pos': 0, 'reward': 99},
                {'key': 'T', 'pos': 19, 'reward': 130},
                {'key': 'D', 'pos': 3, 'reward': 221}],
               [{'key': 'O', 'pos': 14, 'reward': 266},
                {'key': 'P', 'pos': 15, 'reward': 494},
                {'key': 'K', 'pos': 10, 'reward': 418},
                {'key': 'S', 'pos': 18, 'reward': 60}],
               [{'key': 'H', 'pos': 7, 'reward': 316},
                {'key': 'R', 'pos': 17, 'reward': 501},
                {'key': 'S', 'pos': 18, 'reward': 241},
                {'key': 'O', 'pos': 14, 'reward': 158},
                {'key': 'K', 'pos': 10, 'reward': 254},
                {'key': 'J', 'pos': 9, 'reward': 387}],
               [{'key': 'F', 'pos': 5, 'reward': 196},
                {'key': 'T', 'pos': 19, 'reward': 278},
                {'key': 'I', 'pos': 8, 'reward': 248},
                {'key': 'P', 'pos': 15, 'reward': 253},
                {'key': 'A', 'pos': 0, 'reward': 290},
                {'key': 'Q', 'pos': 16, 'reward': 297}],
               [{'key': 'O', 'pos': 14, 'reward': 16},
                {'key': 'P', 'pos': 15, 'reward': 222},
                {'key': 'F', 'pos': 5, 'reward': 282},
                {'key': 'N', 'pos': 13, 'reward': 488}],
               [{'key': 'G', 'pos': 6, 'reward': 211},
                {'key': 'T', 'pos': 19, 'reward': 404},
                {'key': 'F', 'pos': 5, 'reward': 364},
                {'key': 'I', 'pos': 8, 'reward': 484},
                {'key': 'R', 'pos': 17, 'reward': 265},
                {'key': 'A', 'pos': 0, 'reward': 466}],
               [{'key': 'R', 'pos': 17, 'reward': 215},
                {'key': 'E', 'pos': 4, 'reward': 403},
                {'key': 'S', 'pos': 18, 'reward': 251},
                {'key': 'G', 'pos': 6, 'reward': 381},
                {'key': 'N', 'pos': 13, 'reward': 70},
                {'key': 'C', 'pos': 2, 'reward': 6}],
               [{'key': 'M', 'pos': 12, 'reward': 310},
                {'key': 'T', 'pos': 19, 'reward': 315},
                {'key': 'D', 'pos': 3, 'reward': 218},
                {'key': 'I', 'pos': 8, 'reward': 246},
                {'key': 'C', 'pos': 2, 'reward': 315}]]

population = ['A',
              'B',
              'C',
              'D',
              'E',
              'F',
              'G',
              'H',
              'I',
              'J',
              'K',
              'L',
              'M',
              'N',
              'O',
              'P',
              'Q',
              'R',
              'S',
              'T']


# from seqopt.test_input import *
# from seqopt import model
# progress = model.callbacks.Progress(patience=2, do_stop=True)
# scorer = model.scorers.MinMaxNorm(per_episode=False, agg_strategy='mean')
# selector = model.selectors.MaxRelative(cutoff_ratio=0.50)
# seq_opt = model.SeqOpt(scorer=scorer,
#                        selector=selector,
#                        progress=progress,
#                        episodes=20,
#                        n_try=2,
#                        add_to='last',
#                        opt_interval=2,
#                        reset_experiment=True,
#                        population=population
#                        )
# # for ix,feed in enumerate(input_feeds):
# #   seq_opt.opt(feed)
# tour=0
# while tour < len(input_feeds):
#   seq_opt.opt(input_feeds[tour])
#   tour+=1